require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeachingAssignmentsController do

  # This should return the minimal set of attributes required to create a valid
  # TeachingAssignment. As you add validations to TeachingAssignment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "teacher_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TeachingAssignmentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all teaching_assignments as @teaching_assignments" do
      teaching_assignment = TeachingAssignment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:teaching_assignments).should eq([teaching_assignment])
    end
  end

  describe "GET show" do
    it "assigns the requested teaching_assignment as @teaching_assignment" do
      teaching_assignment = TeachingAssignment.create! valid_attributes
      get :show, {:id => teaching_assignment.to_param}, valid_session
      assigns(:teaching_assignment).should eq(teaching_assignment)
    end
  end

  describe "GET new" do
    it "assigns a new teaching_assignment as @teaching_assignment" do
      get :new, {}, valid_session
      assigns(:teaching_assignment).should be_a_new(TeachingAssignment)
    end
  end

  describe "GET edit" do
    it "assigns the requested teaching_assignment as @teaching_assignment" do
      teaching_assignment = TeachingAssignment.create! valid_attributes
      get :edit, {:id => teaching_assignment.to_param}, valid_session
      assigns(:teaching_assignment).should eq(teaching_assignment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TeachingAssignment" do
        expect {
          post :create, {:teaching_assignment => valid_attributes}, valid_session
        }.to change(TeachingAssignment, :count).by(1)
      end

      it "assigns a newly created teaching_assignment as @teaching_assignment" do
        post :create, {:teaching_assignment => valid_attributes}, valid_session
        assigns(:teaching_assignment).should be_a(TeachingAssignment)
        assigns(:teaching_assignment).should be_persisted
      end

      it "redirects to the created teaching_assignment" do
        post :create, {:teaching_assignment => valid_attributes}, valid_session
        response.should redirect_to(TeachingAssignment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved teaching_assignment as @teaching_assignment" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeachingAssignment.any_instance.stub(:save).and_return(false)
        post :create, {:teaching_assignment => { "teacher_id" => "invalid value" }}, valid_session
        assigns(:teaching_assignment).should be_a_new(TeachingAssignment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeachingAssignment.any_instance.stub(:save).and_return(false)
        post :create, {:teaching_assignment => { "teacher_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested teaching_assignment" do
        teaching_assignment = TeachingAssignment.create! valid_attributes
        # Assuming there are no other teaching_assignments in the database, this
        # specifies that the TeachingAssignment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TeachingAssignment.any_instance.should_receive(:update_attributes).with({ "teacher_id" => "1" })
        put :update, {:id => teaching_assignment.to_param, :teaching_assignment => { "teacher_id" => "1" }}, valid_session
      end

      it "assigns the requested teaching_assignment as @teaching_assignment" do
        teaching_assignment = TeachingAssignment.create! valid_attributes
        put :update, {:id => teaching_assignment.to_param, :teaching_assignment => valid_attributes}, valid_session
        assigns(:teaching_assignment).should eq(teaching_assignment)
      end

      it "redirects to the teaching_assignment" do
        teaching_assignment = TeachingAssignment.create! valid_attributes
        put :update, {:id => teaching_assignment.to_param, :teaching_assignment => valid_attributes}, valid_session
        response.should redirect_to(teaching_assignment)
      end
    end

    describe "with invalid params" do
      it "assigns the teaching_assignment as @teaching_assignment" do
        teaching_assignment = TeachingAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeachingAssignment.any_instance.stub(:save).and_return(false)
        put :update, {:id => teaching_assignment.to_param, :teaching_assignment => { "teacher_id" => "invalid value" }}, valid_session
        assigns(:teaching_assignment).should eq(teaching_assignment)
      end

      it "re-renders the 'edit' template" do
        teaching_assignment = TeachingAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeachingAssignment.any_instance.stub(:save).and_return(false)
        put :update, {:id => teaching_assignment.to_param, :teaching_assignment => { "teacher_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested teaching_assignment" do
      teaching_assignment = TeachingAssignment.create! valid_attributes
      expect {
        delete :destroy, {:id => teaching_assignment.to_param}, valid_session
      }.to change(TeachingAssignment, :count).by(-1)
    end

    it "redirects to the teaching_assignments list" do
      teaching_assignment = TeachingAssignment.create! valid_attributes
      delete :destroy, {:id => teaching_assignment.to_param}, valid_session
      response.should redirect_to(teaching_assignments_url)
    end
  end

end
